# Generated by Django 4.1.1 on 2023-03-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сооружение',
                'verbose_name_plural': 'Сооружения',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('measurement_scale', models.SmallIntegerField(default=1, help_text='Во сколько раз вводимые значения больше действительных', verbose_name='Масштаб измерений')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='RodClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_mass', models.SmallIntegerField(blank=True, null=True, verbose_name='Всего, кг')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolumesCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes_calcs', to='calc.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Расчет объема',
                'verbose_name_plural': 'Расчеты объемов',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('volumes_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='calc.volumescalc', verbose_name='Расчет объема')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='calc.construction', verbose_name='Сооружение')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
        migrations.CreateModel(
            name='UnitsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_calcs', to='calc.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Расчет единиц',
                'verbose_name_plural': 'Расчеты единиц',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('units_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='calc.unitscalc', verbose_name='Расчет единиц')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SquaresCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares_calcs', to='calc.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Расчет площади',
                'verbose_name_plural': 'Расчеты площадей',
            },
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('squares_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='calc.squarescalc', verbose_name='Расчет площади')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='RodsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_mass', models.SmallIntegerField(blank=True, null=True, verbose_name='Всего, кг')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rods_calcs', to='calc.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Расчет армирования',
                'verbose_name_plural': 'Расчеты армирования',
            },
        ),
        migrations.CreateModel(
            name='RodDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_mass', models.SmallIntegerField(blank=True, null=True, verbose_name='Всего, кг')),
                ('rod_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rod_diameters', to='calc.rodclass', verbose_name='Класс арматуры')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rodclass',
            name='rods_calc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rod_classes', to='calc.rodscalc', verbose_name='Армирование'),
        ),
        migrations.CreateModel(
            name='Rod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('length_1', models.SmallIntegerField(verbose_name='Длина 1 уч., мм')),
                ('quantity_1', models.SmallIntegerField(default=1, verbose_name='Кол-во 1 уч., шт')),
                ('length_2', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 2 уч., мм')),
                ('quantity_2', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 2 уч., шт')),
                ('length_3', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 3 уч., мм')),
                ('quantity_3', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 3 уч., шт')),
                ('length_4', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 4 уч., мм')),
                ('quantity_4', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 4 уч., шт')),
                ('quantity', models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во, шт')),
                ('length', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина, м')),
                ('mass_of_single_rod', models.SmallIntegerField(blank=True, null=True, verbose_name='Масса стержня, кг')),
                ('mass_of_rods', models.SmallIntegerField(blank=True, null=True, verbose_name='Масса позиции, м')),
                ('diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rods', to='calc.roddiameter', verbose_name='Диаметр, мм')),
                ('rod_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rods', to='calc.rodclass', verbose_name='Класс арматуры')),
                ('rods_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rods', to='calc.rodscalc', verbose_name='Армирование')),
            ],
            options={
                'verbose_name': 'Стержень',
                'verbose_name_plural': 'Стержни',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='LengthsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lengths_calcs', to='calc.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Расчет длины',
                'verbose_name_plural': 'Расчеты длин',
            },
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lengths_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lengths', to='calc.lengthscalc', verbose_name='Расчет длины')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='calc.version', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='calc.folder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='construction',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='constructions', to='calc.site', verbose_name='Объект'),
        ),
    ]
