# Generated by Django 4.1.1 on 2023-03-04 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('measurement_scale', models.SmallIntegerField(default=1, help_text='Во сколько раз вводимые значения больше действительных', verbose_name='Масштаб измерений')),
                ('engineer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='account.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='VolumesCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes_calcs', to='calc.element', verbose_name='Элемент')),
            ],
        ),
        migrations.CreateModel(
            name='UnitsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_calcs', to='calc.element', verbose_name='Элемент')),
            ],
        ),
        migrations.CreateModel(
            name='SquaresCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares_calcs', to='calc.element', verbose_name='Элемент')),
            ],
        ),
        migrations.CreateModel(
            name='RodsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rods_calcs', to='calc.element', verbose_name='Элемент')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('diameter', models.SmallIntegerField(blank=True, null=True, verbose_name='Диаметр, мм')),
                ('arm_class', models.CharField(blank=True, max_length=30, null=True, verbose_name='Класс арматуры')),
                ('length_1', models.SmallIntegerField(verbose_name='Длина 1 уч., мм')),
                ('quantity_1', models.SmallIntegerField(default=1, verbose_name='Кол-во 1 уч., шт')),
                ('length_2', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 2 уч., мм')),
                ('quantity_2', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 2 уч., шт')),
                ('length_3', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 3 уч., мм')),
                ('quantity_3', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 3 уч., шт')),
                ('length_4', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 4 уч., мм')),
                ('quantity_4', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 4 уч., шт')),
                ('quantity', models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во, шт')),
                ('rods_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rods', to='calc.rodscalc', verbose_name='Армирование')),
            ],
            options={
                'verbose_name': 'Стержень',
                'verbose_name_plural': 'Стержни',
                'ordering': ('title',),
            },
        ),
    ]
