# Generated by Django 4.1.1 on 2023-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='diameter',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Диаметр, мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='rod_class',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Класс арматуры'),
        ),
    ]
