# Generated by Django 4.1.1 on 2022-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_element_engineer_element_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rod',
            name='arm_class',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rod',
            name='diameter',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rod',
            name='length',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rod',
            name='mass_of_meter',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rod',
            name='mass_of_position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rod',
            name='mass_of_rod',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
