# Generated by Django 4.1.1 on 2023-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_element_measurement_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='mass_of_rods',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса позиции, кг'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='mass_of_single_rod',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса стержня, кг'),
        ),
    ]
