# Generated by Django 4.1.1 on 2022-11-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_rod_arm_class_rod_diameter_rod_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rod',
            name='mass_of_meter',
        ),
        migrations.RemoveField(
            model_name='rod',
            name='mass_of_position',
        ),
        migrations.RemoveField(
            model_name='rod',
            name='mass_of_rod',
        ),
    ]
