# Generated by Django 4.1.1 on 2022-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_rod_mass_of_meter_remove_rod_mass_of_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='arm_class',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Класс арматуры'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='diameter',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Диаметр'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
    ]
