# Generated by Django 4.1.1 on 2023-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_rod_diameter_alter_rod_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кол-во, шт.'),
        ),
    ]
