# Generated by Django 4.1.1 on 2022-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_rod_arm_class_alter_rod_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rod',
            name='quantity',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во, шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='diameter',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Диаметр, мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Длина, мм'),
        ),
    ]
