# Generated by Django 4.1.1 on 2023-06-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_alter_rod_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rod',
            name='length_3',
        ),
        migrations.RemoveField(
            model_name='rod',
            name='length_4',
        ),
        migrations.RemoveField(
            model_name='rod',
            name='quantity_3',
        ),
        migrations.RemoveField(
            model_name='rod',
            name='quantity_4',
        ),
    ]
