# Generated by Django 4.1.1 on 2022-12-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_alter_element_title_alter_rod_arm_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rod',
            options={'ordering': ('title',), 'verbose_name': 'Стержень', 'verbose_name_plural': 'Стержни'},
        ),
    ]
