# Generated by Django 4.1.1 on 2023-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_remove_rod_length_3_remove_rod_length_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина, мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length_1',
            field=models.FloatField(verbose_name='Длина 1 уч., мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина 2 уч., мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во, шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_1',
            field=models.FloatField(default=1, verbose_name='Кол-во 1 уч., шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_2',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Кол-во 2 уч., шт'),
        ),
    ]
