# Generated by Django 4.1.1 on 2023-06-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_alter_rod_length_alter_rod_length_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rod',
            name='length_3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 3 уч., мм'),
        ),
        migrations.AddField(
            model_name='rod',
            name='quantity_3',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 3 уч., шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во, шт'),
        ),
    ]
