# Generated by Django 4.1.1 on 2023-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_alter_element_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='arm_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс арматуры'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='diameter',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Диаметр, мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина, мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во, шт'),
        ),
    ]
