# Generated by Django 4.1.1 on 2023-06-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_alter_rod_length_1_alter_rod_length_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='length_1',
            field=models.PositiveIntegerField(verbose_name='Длина 1 уч., мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина 2 уч., мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина 3 уч., мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во, шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_1',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во 1 уч., шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_2',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 2 уч., шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_3',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во 3 уч., шт'),
        ),
    ]
