# Generated by Django 4.1.1 on 2023-03-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_alter_rod_arm_class_alter_rod_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rod',
            name='length',
        ),
        migrations.AddField(
            model_name='rod',
            name='length_1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 1 уч., мм'),
        ),
        migrations.AddField(
            model_name='rod',
            name='length_2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 2 уч., мм'),
        ),
        migrations.AddField(
            model_name='rod',
            name='length_3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 3 уч., мм'),
        ),
        migrations.AddField(
            model_name='rod',
            name='length_4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 4 уч., мм'),
        ),
        migrations.AddField(
            model_name='rod',
            name='quantity_1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во 1 уч., шт'),
        ),
        migrations.AddField(
            model_name='rod',
            name='quantity_2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во 2 уч., шт'),
        ),
        migrations.AddField(
            model_name='rod',
            name='quantity_3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во 3 уч., шт'),
        ),
        migrations.AddField(
            model_name='rod',
            name='quantity_4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во 4 уч., шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='arm_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Класс'),
        ),
    ]
