# Generated by Django 4.1.1 on 2023-07-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_remove_lengthscalc_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='diameter',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='⌀'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='rod_class',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Класс'),
        ),
    ]
