# Generated by Django 4.1.1 on 2023-07-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_alter_rod_diameter_alter_rod_rod_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='rod',
            name='quantity_a',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель A, шт'),
        ),
        migrations.AddField(
            model_name='rod',
            name='quantity_b',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель B, шт'),
        ),
        migrations.AddField(
            model_name='rod',
            name='quantity_c',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель C, шт'),
        ),
    ]
