# Generated by Django 4.1.1 on 2023-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_rod_quantity_a_rod_quantity_b_rod_quantity_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='length_1',
            field=models.PositiveIntegerField(verbose_name='Длина A, мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина B, мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='length_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина C, мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_1',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во n1, шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_2',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во n2, шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_3',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во n3, шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_a',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель K, шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_b',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель L, шт'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_c',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель M, шт'),
        ),
    ]
