# Generated by Django 4.1.1 on 2023-03-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_alter_rod_diameter_alter_rod_length_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='arm_class',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Класс'),
        ),
    ]
