# Generated by Django 4.1.1 on 2023-03-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_alter_rod_arm_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='arm_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс'),
        ),
    ]
