# Generated by Django 4.1.1 on 2023-09-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_alter_rod_quantity_a_alter_rod_quantity_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodscalc',
            name='measurement_scale',
        ),
        migrations.AddField(
            model_name='rodscalc',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество элементов'),
        ),
    ]
