# Generated by Django 4.1.1 on 2023-03-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0021_alter_rod_length_1_alter_rod_length_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rod',
            name='length_2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина 2 уч., мм'),
        ),
        migrations.AlterField(
            model_name='rod',
            name='quantity_1',
            field=models.SmallIntegerField(default=1, verbose_name='Кол-во 1 уч., шт'),
        ),
    ]
