# Generated by Django 4.1.1 on 2024-03-13 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0021_construction_update_date_element_update_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construction',
            options={'ordering': ('-update_date',), 'verbose_name': 'Сооружение', 'verbose_name_plural': 'Сооружения'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ('title',), 'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('-update_date',), 'verbose_name': 'Папка', 'verbose_name_plural': 'Папки'},
        ),
        migrations.AlterModelOptions(
            name='rodclass',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='roddiameter',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='rodscalc',
            options={'ordering': ('-update_date',), 'verbose_name': 'Расчет армирования', 'verbose_name_plural': 'Расчеты армирования'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('-update_date',), 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('-update_date',), 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.CreateModel(
            name='VolumesCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('total_volume', models.FloatField(blank=True, null=True, verbose_name='Всего, м3')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество элементов')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes_calcs', to='calc.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Расчет объема',
                'verbose_name_plural': 'Расчеты объемов',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('is_hole', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отверстие?')),
                ('length', models.PositiveIntegerField(verbose_name='Длина, мм')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина, мм')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота, мм')),
                ('quantity_a', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель F, шт')),
                ('quantity_b', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель G, шт')),
                ('quantity_c', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Множитель H, шт')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во, шт')),
                ('volume_of_single_volume', models.FloatField(blank=True, null=True, verbose_name='Объем ед., м3')),
                ('volume_of_volumes', models.FloatField(blank=True, null=True, verbose_name='Объем общий, м3')),
                ('volumes_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='calc.volumescalc', verbose_name='Расчет объема')),
            ],
            options={
                'verbose_name': 'Объем',
                'verbose_name_plural': 'Объемы',
                'ordering': ('title',),
            },
        ),
    ]
