# Generated by Django 4.1.1 on 2024-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0022_alter_construction_options_alter_element_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='is_hole',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отверстие'),
        ),
    ]
