# Generated by Django 4.1.1 on 2023-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0023_element_measurement_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='measurement_scale',
            field=models.SmallIntegerField(default=1, help_text='Во сколько раз вводимые значения длин больше действительных', verbose_name='Масштаб измерений длины'),
        ),
    ]
