# Generated by Django 4.1.1 on 2023-03-04 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0024_alter_element_measurement_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rod',
            name='element',
        ),
        migrations.AlterField(
            model_name='element',
            name='measurement_scale',
            field=models.SmallIntegerField(default=1, help_text='Во сколько раз вводимые значения больше действительных', verbose_name='Масштаб измерений'),
        ),
        migrations.CreateModel(
            name='VolumesCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes_calcs', to='calc.element', verbose_name='Элемент')),
            ],
        ),
        migrations.CreateModel(
            name='UnitsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_calcs', to='calc.element', verbose_name='Элемент')),
            ],
        ),
        migrations.CreateModel(
            name='SquaresCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares_calcs', to='calc.element', verbose_name='Элемент')),
            ],
        ),
        migrations.CreateModel(
            name='RodsCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rods_calcs', to='calc.element', verbose_name='Элемент')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rod',
            name='rods_calc',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='rods', to='calc.rodscalc', verbose_name='Армирование'),
            preserve_default=False,
        ),
    ]
