from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'calc'

urlpatterns_objects = [
    path(
        'site/<int:pk>/',
        views.site,
        name='site',
    ),
    path(
        'site/create',
        views.site_create,
        name='site_create',
    ),
    path(
        'site/<int:pk>/update',
        views.site_update,
        name='site_update',
    ),
    path(
        'site/<int:pk>/duplicate',
        views.site_duplicate,
        name='site_duplicate',
    ),
    path(
        'site/<int:pk>/delete',
        views.site_delete,
        name='site_delete',
    ),

    path(
        'construction/<int:pk>/',
        views.construction,
        name='construction',
    ),
    path(
        'construction/create',
        views.construction_create,
        name='construction_create',
    ),
    path(
        'construction/<int:pk>/update',
        views.construction_update,
        name='construction_update',
    ),
    path(
        'construction/<int:pk>/duplicate',
        views.construction_duplicate,
        name='construction_duplicate',
    ),
    path(
        'construction/<int:pk>/delete',
        views.construction_delete,
        name='construction_delete',
    ),

    path(
        'version/<int:pk>/',
        views.version,
        name='version',
    ),
    path(
        'version/create',
        views.version_create,
        name='version_create',
    ),
    path(
        'version/<int:pk>/update',
        views.version_update,
        name='version_update',
    ),
    path(
        'version/<int:pk>/duplicate',
        views.version_duplicate,
        name='version_duplicate',
    ),
    path(
        'version/<int:pk>/delete',
        views.version_delete,
        name='version_delete',
    ),

    path(
        'folder/<int:pk>/',
        views.folder,
        name='folder',
    ),
    path(
        'folder/create',
        views.folder_create,
        name='folder_create',
    ),
    path(
        'folder/<int:pk>/update',
        views.folder_update,
        name='folder_update',
    ),
    path(
        'folder/<int:pk>/duplicate',
        views.folder_duplicate,
        name='folder_duplicate',
    ),
    path(
        'folder/<int:pk>/delete',
        views.folder_delete,
        name='folder_delete',
    ),

    path(
        'element/<int:pk>/',
        views.element,
        name='element',
    ),
    path(
        'element/create',
        views.element_create,
        name='element_create',
    ),
    path(
        'element/<int:pk>/update',
        views.element_update,
        name='element_update',
    ),
    path(
        'element/<int:pk>/duplicate',
        views.element_duplicate,
        name='element_duplicate',
    ),
    path(
        'element/<int:pk>/delete',
        views.element_delete,
        name='element_delete',
    ),
]

urlpatterns_rods_calc = [
    path(
        'rods_calc/<int:pk>/',
        views.RodsCalcDetail.as_view(),
        name='rods_calc',
    ),
    path(
        'rods_calc/create/',
        views.RodsCalcCreate.as_view(),
        name='rods_calc_create',
    ),
    path(
        'rods_calc/<int:pk>/update/',
        views.RodsCalcUpdate.as_view(),
        name='rods_calc_update',
    ),
    path(
        'rods_calc/<int:pk>/duplicate/',
        views.rods_calc_duplicate,
        name='rods_calc_duplicate',
    ),
    path(
        'rods_calc/<int:pk>/delete/',
        views.RodsCalcDelete.as_view(),
        name='rods_calc_delete',
    ),

    path(
        'rod/<int:pk>/duplicate/',
        views.rod_duplicate,
        name='rod_duplicate',
    ),
    path(
        'rod/<int:pk>/delete/',
        views.rod_delete,
        name='rod_delete',
    ),
]

urlpatterns_volumes_calc = [
    path(
        'volumes_calc/<int:pk>/',
        views.VolumesCalcDetail.as_view(),
        name='volumes_calc',
    ),
    path(
        'volumes_calc/create/',
        views.VolumesCalcCreate.as_view(),
        name='volumes_calc_create',
    ),
    path(
        'volumes_calc/<int:pk>/update/',
        views.VolumesCalcUpdate.as_view(),
        name='volumes_calc_update',
    ),
    path(
        'volumes_calc/<int:pk>/duplicate/',
        views.volumes_calc_duplicate,
        name='volumes_calc_duplicate',
    ),
    path(
        'volumes_calc/<int:pk>/delete/',
        views.VolumesCalcDelete.as_view(),
        name='volumes_calc_delete',
    ),

    path(
        'volume/<int:pk>/duplicate/',
        views.volume_duplicate,
        name='volume_duplicate',
    ),
    path(
        'volume/<int:pk>/delete/',
        views.volume_delete,
        name='volume_delete',
    ),
]

urlpatterns_squares_calc = [
    path(
        'squares_calc/<int:pk>/',
        views.SquaresCalcDetail.as_view(),
        name='squares_calc',
    ),
    path(
        'squares_calc/create/',
        views.SquaresCalcCreate.as_view(),
        name='squares_calc_create',
    ),
    path(
        'squares_calc/<int:pk>/update/',
        views.SquaresCalcUpdate.as_view(),
        name='squares_calc_update',
    ),
    path(
        'squares_calc/<int:pk>/duplicate/',
        views.squares_calc_duplicate,
        name='squares_calc_duplicate',
    ),
    path(
        'squares_calc/<int:pk>/delete/',
        views.SquaresCalcDelete.as_view(),
        name='squares_calc_delete',
    ),

    path(
        'square/<int:pk>/duplicate/',
        views.square_duplicate,
        name='square_duplicate',
    ),
    path(
        'square/<int:pk>/delete/',
        views.square_delete,
        name='square_delete',
    ),
]

urlpatterns_lengths_calc = [
    path(
        'lengths_calc/<int:pk>/',
        views.LengthsCalcDetail.as_view(),
        name='lengths_calc',
    ),
    path(
        'lengths_calc/create/',
        views.LengthsCalcCreate.as_view(),
        name='lengths_calc_create',
    ),
    path(
        'lengths_calc/<int:pk>/update/',
        views.LengthsCalcUpdate.as_view(),
        name='lengths_calc_update',
    ),
    path(
        'lengths_calc/<int:pk>/duplicate/',
        views.lengths_calc_duplicate,
        name='lengths_calc_duplicate',
    ),
    path(
        'lengths_calc/<int:pk>/delete/',
        views.LengthsCalcDelete.as_view(),
        name='lengths_calc_delete',
    ),

    path(
        'length/<int:pk>/duplicate/',
        views.length_duplicate,
        name='length_duplicate',
    ),
    path(
        'length/<int:pk>/delete/',
        views.length_delete,
        name='length_delete',
    ),
]

urlpatterns_units_calc = [
    path(
        'units_calc/<int:pk>/',
        views.UnitsCalcDetail.as_view(),
        name='units_calc',
    ),
    path(
        'units_calc/create/',
        views.UnitsCalcCreate.as_view(),
        name='units_calc_create',
    ),
    path(
        'units_calc/<int:pk>/update/',
        views.UnitsCalcUpdate.as_view(),
        name='units_calc_update',
    ),
    path(
        'units_calc/<int:pk>/duplicate/',
        views.units_calc_duplicate,
        name='units_calc_duplicate',
    ),
    path(
        'units_calc/<int:pk>/delete/',
        views.UnitsCalcDelete.as_view(),
        name='units_calc_delete',
    ),

    path(
        'unit/<int:pk>/duplicate/',
        views.unit_duplicate,
        name='unit_duplicate',
    ),
    path(
        'unit/<int:pk>/delete/',
        views.unit_delete,
        name='unit_delete',
    ),
]

urlpatterns = (
        [
            path(
                '',
                views.landing,
                name='landing',
            ),
            path(
                'profile/<str:username>/',
                views.profile,
                name='profile',
            ),
            path(
                'result/<int:pk>/',
                views.result,
                name='result',
            ),
        ]
        + urlpatterns_objects
        + urlpatterns_rods_calc
        + urlpatterns_volumes_calc
        + urlpatterns_squares_calc
        + urlpatterns_lengths_calc
        + urlpatterns_units_calc
)
